#!/bin/bash

if [[ $# -eq 0 ]]; then
  echo "Need commit comment: [./autopush 'comment']"
  exit
else
  echo "COMMENT: " $1
fi

git stash
git pull --rebase
git stash pop

git commit -a -m $1
git push
